# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Bear In Mind' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Bear In Mind
pod 'Firebase/Analytics','6.8.1'
pod 'Firebase/Storage'
pod 'SDWebImageSwiftUI'

  target 'Bear In MindTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Bear In MindUITests' do
    # Pods for testing
  end

end
